"""
Interoperability layer.

Typical usage::

    import decent_array.interoperability as iop

    iop.set_backend("numpy")
    a = iop.zeros((3, 3))
    iop.set_seed(42)  # Optional: set RNG seed for reproducibility
    s = iop.normal(shape=(2,))

"""

from ._backend_manager import set_backend
from ._decorators import autodecorate_cost_method
from ._iop.functions import (
    absolute,
    add,
    all,  # noqa: A004
    any,  # noqa: A004
    argmax,
    argmin,
    astype,
    bitwise_and,
    copy,
    device_of,
    device_to_native,
    diag,
    div,
    dot,
    eq,
    eye,
    eye_like,
    from_numpy,
    from_numpy_like,
    ge,
    get_item,
    gt,
    iadd,
    idiv,
    imul,
    isub,
    le,
    lt,
    matmul,
    max,  # noqa: A004
    maximum,
    mean,
    min,  # noqa: A004
    mul,
    ndim,
    ne,
    negative,
    norm,
    ones,
    ones_like,
    pow,  # noqa: A004
    reshape,
    set_item,
    shape,
    sign,
    size,
    sqrt,
    squeeze,
    stack,
    sub,
    sum,  # noqa: A004
    to_array,
    to_numpy,
    transpose,
    unsqueeze,
    zeros,
    zeros_like,
)
from ._iop.rng import (
    choice,
    derive_seed,
    get_rng_state,
    get_seed,
    normal,
    normal_like,
    set_rng_state,
    set_seed,
    uniform,
    uniform_like,
)

__all__ = [
    "absolute",
    "add",
    "all",
    "any",
    "argmax",
    "argmin",
    "astype",
    "autodecorate_cost_method",
    "bitwise_and",
    "choice",
    "copy",
    "derive_seed",
    "device_of",
    "device_to_native",
    "diag",
    "div",
    "dot",
    "eq",
    "eye",
    "eye_like",
    "from_numpy",
    "from_numpy_like",
    "ge",
    "get_item",
    "get_rng_state",
    "get_seed",
    "gt",
    "iadd",
    "idiv",
    "imul",
    "isub",
    "le",
    "lt",
    "matmul",
    "max",
    "maximum",
    "mean",
    "min",
    "mul",
    "ndim",
    "ne",
    "negative",
    "norm",
    "normal",
    "normal_like",
    "ones",
    "ones_like",
    "pow",
    "reshape",
    "set_backend",
    "set_item",
    "set_rng_state",
    "set_seed",
    "shape",
    "sign",
    "size",
    "sqrt",
    "squeeze",
    "stack",
    "sub",
    "sum",
    "to_array",
    "to_numpy",
    "transpose",
    "uniform",
    "uniform_like",
    "unsqueeze",
    "zeros",
    "zeros_like",
]
